### ISSUE TITLE
Support Swift Package Manager?

### ISSUE THREAD

**Issue by edl00k** [phrase/ios-sdk#18]

**Comment by winkelsdorf** [comment]
@edl00k Thank you for your suggestion! 

Swift Package Manager will probably support binary dependencies with the release of Swift 5.3. The current Swift version is 5.2.4, released on May 20, 2020. 

But we are following Apple's development in this area, it is something that is on our roadmap for later this year. Using SPM probably requires the use of `xcframeworks` bundles, which are currently unsupported below Xcode 11 and in Carthage afaik. In order to support a wide range of platforms and build tools, the build process will need to be adjusted once Swift 5.3 is ready.

We are closing this for now, as it is being tracked internally and does not work with the currently available Swift 5.2.4.

**Comment by edl00k** [comment]
got it, thanks for the answer

**Comment by winkelsdorf** [comment]
@edl00k You're welcome!
